<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251124071139 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE team_invitations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, role VARCHAR(50) NOT NULL, token VARCHAR(64) NOT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, responded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, team_id INT NOT NULL, invited_by_id INT NOT NULL, invited_user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C817FFE35F37A13B ON team_invitations (token)');
        $this->addSql('CREATE INDEX IDX_C817FFE3296CD8AE ON team_invitations (team_id)');
        $this->addSql('CREATE INDEX IDX_C817FFE3A7B4A7E3 ON team_invitations (invited_by_id)');
        $this->addSql('CREATE INDEX IDX_C817FFE3C58DAD6E ON team_invitations (invited_user_id)');
        $this->addSql('CREATE TABLE team_members (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(50) NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, team_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BAD9A3C8296CD8AE ON team_members (team_id)');
        $this->addSql('CREATE INDEX IDX_BAD9A3C8A76ED395 ON team_members (user_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_team_user ON team_members (team_id, user_id)');
        $this->addSql('CREATE TABLE teams (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, avatar_url VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_96C22258989D9B62 ON teams (slug)');
        $this->addSql('CREATE INDEX IDX_96C222587E3C61F9 ON teams (owner_id)');
        $this->addSql('ALTER TABLE team_invitations ADD CONSTRAINT FK_C817FFE3296CD8AE FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_invitations ADD CONSTRAINT FK_C817FFE3A7B4A7E3 FOREIGN KEY (invited_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_invitations ADD CONSTRAINT FK_C817FFE3C58DAD6E FOREIGN KEY (invited_user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_members ADD CONSTRAINT FK_BAD9A3C8296CD8AE FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_members ADD CONSTRAINT FK_BAD9A3C8A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE teams ADD CONSTRAINT FK_96C222587E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE projects ADD team_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE projects ALTER preview_deployments_enabled DROP DEFAULT');
        $this->addSql('ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A4296CD8AE FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_5C93B3A4296CD8AE ON projects (team_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE team_invitations DROP CONSTRAINT FK_C817FFE3296CD8AE');
        $this->addSql('ALTER TABLE team_invitations DROP CONSTRAINT FK_C817FFE3A7B4A7E3');
        $this->addSql('ALTER TABLE team_invitations DROP CONSTRAINT FK_C817FFE3C58DAD6E');
        $this->addSql('ALTER TABLE team_members DROP CONSTRAINT FK_BAD9A3C8296CD8AE');
        $this->addSql('ALTER TABLE team_members DROP CONSTRAINT FK_BAD9A3C8A76ED395');
        $this->addSql('ALTER TABLE teams DROP CONSTRAINT FK_96C222587E3C61F9');
        $this->addSql('DROP TABLE team_invitations');
        $this->addSql('DROP TABLE team_members');
        $this->addSql('DROP TABLE teams');
        $this->addSql('ALTER TABLE projects DROP CONSTRAINT FK_5C93B3A4296CD8AE');
        $this->addSql('DROP INDEX IDX_5C93B3A4296CD8AE');
        $this->addSql('ALTER TABLE projects DROP team_id');
        $this->addSql('ALTER TABLE projects ALTER preview_deployments_enabled SET DEFAULT false');
    }
}
