<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251124182525 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE environment_variables (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, key VARCHAR(255) NOT NULL, value TEXT NOT NULL, is_secret BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_env_var_project ON environment_variables (project_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_project_key ON environment_variables (project_id, key)');
        $this->addSql('ALTER TABLE environment_variables ADD CONSTRAINT FK_4AF8BED8166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE environment_variables DROP CONSTRAINT FK_4AF8BED8166D1F9C');
        $this->addSql('DROP TABLE environment_variables');
    }
}
