<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251123173328 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE preview_deployments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pr_number INT NOT NULL, pr_title VARCHAR(255) NOT NULL, branch VARCHAR(100) NOT NULL, commit_hash VARCHAR(64) DEFAULT NULL, commit_message TEXT DEFAULT NULL, pr_author VARCHAR(100) DEFAULT NULL, status VARCHAR(50) NOT NULL, preview_url VARCHAR(255) DEFAULT NULL, subdomain VARCHAR(100) DEFAULT NULL, docker_image VARCHAR(255) DEFAULT NULL, docker_tag VARCHAR(100) DEFAULT NULL, container_id VARCHAR(100) DEFAULT NULL, container_port INT DEFAULT NULL, build_log TEXT DEFAULT NULL, error_message TEXT DEFAULT NULL, github_comment_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deployed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, destroyed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8C2708BD166D1F9C ON preview_deployments (project_id)');
        $this->addSql('CREATE INDEX idx_preview_project_pr ON preview_deployments (project_id, pr_number)');
        $this->addSql('ALTER TABLE preview_deployments ADD CONSTRAINT FK_8C2708BD166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE projects ADD preview_deployments_enabled BOOLEAN DEFAULT FALSE NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE preview_deployments DROP CONSTRAINT FK_8C2708BD166D1F9C');
        $this->addSql('DROP TABLE preview_deployments');
        $this->addSql('ALTER TABLE projects DROP preview_deployments_enabled');
    }
}
