<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251123163305 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE domain_purchases (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, domain VARCHAR(255) NOT NULL, tld VARCHAR(20) NOT NULL, provider VARCHAR(50) NOT NULL, status VARCHAR(50) NOT NULL, years INT NOT NULL, price NUMERIC(10, 2) NOT NULL, currency VARCHAR(3) NOT NULL, provider_domain_id VARCHAR(255) DEFAULT NULL, provider_order_id VARCHAR(255) DEFAULT NULL, provider_transaction_id VARCHAR(255) DEFAULT NULL, registrant_info JSON DEFAULT NULL, nameservers JSON DEFAULT NULL, error_message TEXT DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, project_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4C14E3B0A76ED395 ON domain_purchases (user_id)');
        $this->addSql('CREATE INDEX IDX_4C14E3B0166D1F9C ON domain_purchases (project_id)');
        $this->addSql('ALTER TABLE domain_purchases ADD CONSTRAINT FK_4C14E3B0A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE domain_purchases ADD CONSTRAINT FK_4C14E3B0166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE domain_purchases DROP CONSTRAINT FK_4C14E3B0A76ED395');
        $this->addSql('ALTER TABLE domain_purchases DROP CONSTRAINT FK_4C14E3B0166D1F9C');
        $this->addSql('DROP TABLE domain_purchases');
    }
}
