<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251124191210 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE databases (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, name VARCHAR(100) NOT NULL, container_name VARCHAR(255) DEFAULT NULL, container_id VARCHAR(255) DEFAULT NULL, status VARCHAR(20) NOT NULL, version VARCHAR(50) DEFAULT NULL, port INT DEFAULT NULL, username VARCHAR(100) NOT NULL, password VARCHAR(255) NOT NULL, database_name VARCHAR(100) DEFAULT NULL, connection_string TEXT DEFAULT NULL, configuration JSON DEFAULT NULL, memory_size_mb INT DEFAULT NULL, cpu_limit DOUBLE PRECISION DEFAULT NULL, disk_size_mb BIGINT DEFAULT NULL, error_message TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, stopped_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, project_id INT NOT NULL, server_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_database_project ON databases (project_id)');
        $this->addSql('CREATE INDEX idx_database_server ON databases (server_id)');
        $this->addSql('CREATE INDEX idx_database_status ON databases (status)');
        $this->addSql('ALTER TABLE databases ADD CONSTRAINT FK_C71191C2166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE databases ADD CONSTRAINT FK_C71191C21844E6B7 FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE databases DROP CONSTRAINT FK_C71191C2166D1F9C');
        $this->addSql('ALTER TABLE databases DROP CONSTRAINT FK_C71191C21844E6B7');
        $this->addSql('DROP TABLE databases');
    }
}
