<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251122185807 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE projects (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, repository_url VARCHAR(255) DEFAULT NULL, repository_name VARCHAR(255) DEFAULT NULL, branch VARCHAR(100) DEFAULT NULL, framework VARCHAR(50) NOT NULL, build_command VARCHAR(255) DEFAULT NULL, install_command VARCHAR(255) DEFAULT NULL, output_directory VARCHAR(255) DEFAULT NULL, root_directory VARCHAR(255) DEFAULT NULL, environment_variables JSON DEFAULT NULL, status VARCHAR(20) NOT NULL, production_url VARCHAR(255) DEFAULT NULL, custom_domain VARCHAR(255) DEFAULT NULL, auto_deploy_enabled BOOLEAN NOT NULL, last_deployed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5C93B3A4989D9B62 ON projects (slug)');
        $this->addSql('CREATE INDEX IDX_5C93B3A47E3C61F9 ON projects (owner_id)');
        $this->addSql('ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A47E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE projects DROP CONSTRAINT FK_5C93B3A47E3C61F9');
        $this->addSql('DROP TABLE projects');
    }
}
