<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251122191013 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE deployments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, trigger VARCHAR(20) NOT NULL, commit_hash VARCHAR(40) DEFAULT NULL, commit_message VARCHAR(255) DEFAULT NULL, branch VARCHAR(100) DEFAULT NULL, docker_image VARCHAR(255) DEFAULT NULL, docker_tag VARCHAR(100) DEFAULT NULL, build_logs TEXT DEFAULT NULL, deploy_logs TEXT DEFAULT NULL, error_message TEXT DEFAULT NULL, build_duration INT DEFAULT NULL, deploy_duration INT DEFAULT NULL, deployment_url VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, build_started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, build_finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deploy_started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deploy_finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, project_id INT NOT NULL, triggered_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_373C43D5166D1F9C ON deployments (project_id)');
        $this->addSql('CREATE INDEX IDX_373C43D563C5923F ON deployments (triggered_by_id)');
        $this->addSql('CREATE INDEX idx_deployment_status ON deployments (status)');
        $this->addSql('CREATE INDEX idx_deployment_created ON deployments (created_at)');
        $this->addSql('CREATE TABLE servers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, ip_address VARCHAR(45) NOT NULL, ssh_port INT NOT NULL, ssh_user VARCHAR(50) NOT NULL, ssh_private_key TEXT DEFAULT NULL, provider VARCHAR(20) NOT NULL, provider_id VARCHAR(255) DEFAULT NULL, status VARCHAR(20) NOT NULL, docker_installed BOOLEAN DEFAULT NULL, docker_version VARCHAR(50) DEFAULT NULL, cpu_cores INT DEFAULT NULL, memory_mb INT DEFAULT NULL, disk_gb INT DEFAULT NULL, os VARCHAR(50) DEFAULT NULL, region VARCHAR(50) DEFAULT NULL, last_error TEXT DEFAULT NULL, last_connected_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4F8AF5F77E3C61F9 ON servers (owner_id)');
        $this->addSql('ALTER TABLE deployments ADD CONSTRAINT FK_373C43D5166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE deployments ADD CONSTRAINT FK_373C43D563C5923F FOREIGN KEY (triggered_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE servers ADD CONSTRAINT FK_4F8AF5F77E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE deployments DROP CONSTRAINT FK_373C43D5166D1F9C');
        $this->addSql('ALTER TABLE deployments DROP CONSTRAINT FK_373C43D563C5923F');
        $this->addSql('ALTER TABLE servers DROP CONSTRAINT FK_4F8AF5F77E3C61F9');
        $this->addSql('DROP TABLE deployments');
        $this->addSql('DROP TABLE servers');
    }
}
