<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251124185746 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE alert_rules (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, metric VARCHAR(50) NOT NULL, operator VARCHAR(10) NOT NULL, threshold DOUBLE PRECISION NOT NULL, duration INT NOT NULL, channel VARCHAR(50) NOT NULL, enabled BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_triggered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_63C06ED7166D1F9C ON alert_rules (project_id)');
        $this->addSql('CREATE INDEX idx_alert_project_enabled ON alert_rules (project_id, enabled)');
        $this->addSql('CREATE TABLE alerts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, severity VARCHAR(50) NOT NULL, title VARCHAR(255) NOT NULL, message TEXT NOT NULL, metadata JSON DEFAULT NULL, resolved BOOLEAN NOT NULL, resolved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, notification_sent BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, rule_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F77AC06B166D1F9C ON alerts (project_id)');
        $this->addSql('CREATE INDEX IDX_F77AC06B744E0351 ON alerts (rule_id)');
        $this->addSql('CREATE INDEX idx_alert_project_time ON alerts (project_id, created_at)');
        $this->addSql('CREATE INDEX idx_alert_resolved ON alerts (resolved)');
        $this->addSql('CREATE TABLE health_checks (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, response_time INT DEFAULT NULL, cpu_usage DOUBLE PRECISION DEFAULT NULL, memory_usage DOUBLE PRECISION DEFAULT NULL, memory_usage_bytes BIGINT DEFAULT NULL, memory_limit_bytes BIGINT DEFAULT NULL, disk_usage DOUBLE PRECISION DEFAULT NULL, is_container_running BOOLEAN NOT NULL, http_status_code INT DEFAULT NULL, error_message TEXT DEFAULT NULL, checked_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E466E8FC166D1F9C ON health_checks (project_id)');
        $this->addSql('CREATE INDEX idx_health_project_time ON health_checks (project_id, checked_at)');
        $this->addSql('CREATE INDEX idx_health_status ON health_checks (status)');
        $this->addSql('ALTER TABLE alert_rules ADD CONSTRAINT FK_63C06ED7166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE alerts ADD CONSTRAINT FK_F77AC06B166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE alerts ADD CONSTRAINT FK_F77AC06B744E0351 FOREIGN KEY (rule_id) REFERENCES alert_rules (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE health_checks ADD CONSTRAINT FK_E466E8FC166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE alert_rules DROP CONSTRAINT FK_63C06ED7166D1F9C');
        $this->addSql('ALTER TABLE alerts DROP CONSTRAINT FK_F77AC06B166D1F9C');
        $this->addSql('ALTER TABLE alerts DROP CONSTRAINT FK_F77AC06B744E0351');
        $this->addSql('ALTER TABLE health_checks DROP CONSTRAINT FK_E466E8FC166D1F9C');
        $this->addSql('DROP TABLE alert_rules');
        $this->addSql('DROP TABLE alerts');
        $this->addSql('DROP TABLE health_checks');
    }
}
