<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251124195828 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE backups (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(50) NOT NULL, status VARCHAR(50) NOT NULL, method VARCHAR(50) NOT NULL, compression VARCHAR(50) NOT NULL, file_path TEXT DEFAULT NULL, file_size_bytes BIGINT DEFAULT NULL, retention_days INT DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, error_message TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, restored_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, metadata JSON DEFAULT NULL, database_id INT NOT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C451D019B03A8386 ON backups (created_by_id)');
        $this->addSql('CREATE INDEX idx_backup_database ON backups (database_id)');
        $this->addSql('CREATE INDEX idx_backup_status ON backups (status)');
        $this->addSql('CREATE INDEX idx_backup_created ON backups (created_at)');
        $this->addSql('ALTER TABLE backups ADD CONSTRAINT FK_C451D019F0AA09DB FOREIGN KEY (database_id) REFERENCES databases (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE backups ADD CONSTRAINT FK_C451D019B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE backups DROP CONSTRAINT FK_C451D019F0AA09DB');
        $this->addSql('ALTER TABLE backups DROP CONSTRAINT FK_C451D019B03A8386');
        $this->addSql('DROP TABLE backups');
    }
}
