<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251124074638 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activity_logs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(50) NOT NULL, entity_type VARCHAR(50) DEFAULT NULL, entity_id INT DEFAULT NULL, entity_name VARCHAR(255) DEFAULT NULL, description VARCHAR(500) NOT NULL, metadata JSON DEFAULT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent VARCHAR(500) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, team_id INT DEFAULT NULL, project_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F34B1DCEA76ED395 ON activity_logs (user_id)');
        $this->addSql('CREATE INDEX IDX_F34B1DCE296CD8AE ON activity_logs (team_id)');
        $this->addSql('CREATE INDEX IDX_F34B1DCE166D1F9C ON activity_logs (project_id)');
        $this->addSql('CREATE INDEX idx_activity_created ON activity_logs (created_at)');
        $this->addSql('CREATE INDEX idx_activity_action ON activity_logs (action)');
        $this->addSql('CREATE INDEX idx_activity_entity ON activity_logs (entity_type, entity_id)');
        $this->addSql('ALTER TABLE activity_logs ADD CONSTRAINT FK_F34B1DCEA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activity_logs ADD CONSTRAINT FK_F34B1DCE296CD8AE FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE activity_logs ADD CONSTRAINT FK_F34B1DCE166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE deployments ALTER is_current_production DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activity_logs DROP CONSTRAINT FK_F34B1DCEA76ED395');
        $this->addSql('ALTER TABLE activity_logs DROP CONSTRAINT FK_F34B1DCE296CD8AE');
        $this->addSql('ALTER TABLE activity_logs DROP CONSTRAINT FK_F34B1DCE166D1F9C');
        $this->addSql('DROP TABLE activity_logs');
        $this->addSql('ALTER TABLE deployments ALTER is_current_production SET DEFAULT false');
    }
}
