<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251123111516 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE domains (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, domain VARCHAR(255) NOT NULL, status VARCHAR(20) NOT NULL, is_primary BOOLEAN NOT NULL, dns_verified BOOLEAN DEFAULT NULL, dns_verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ssl_enabled BOOLEAN DEFAULT NULL, ssl_issued_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ssl_expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_error TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8C7BBF9D166D1F9C ON domains (project_id)');
        $this->addSql('ALTER TABLE domains ADD CONSTRAINT FK_8C7BBF9D166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE domains DROP CONSTRAINT FK_8C7BBF9D166D1F9C');
        $this->addSql('DROP TABLE domains');
    }
}
